CREATE DATABASE PEMDB
AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING SYSTEM PAGESIZE 32768;
CONNECT TO PEMDB;
UPDATE DATABASE CONFIG FOR PEMDB USING LOGFILSIZ 65536;
UPDATE DATABASE CONFIG FOR PEMDB USING LOGPRIMARY 40;
UPDATE DATABASE CONFIG FOR PEMDB USING NUM_LOG_SPAN 32;
UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_MAINT ON;
UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_TBL_MAINT ON;
UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_RUNSTATS ON;
UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_REORG ON;
UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_DB_BACKUP ON;
CREATE USER TEMPORARY TABLESPACE B2BUSERTEMP PAGESIZE 32K BUFFERPOOL IBMDEFAULTBP;
CREATE BUFFERPOOL PEMDB_04KBP IMMEDIATE SIZE 1000 PAGESIZE 4K;
CREATE REGULAR TABLESPACE TS_REG04_PEMDB PAGESIZE 4K BUFFERPOOL PEMDB_04KBP;
CREATE BUFFERPOOL PEMDB_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
CREATE REGULAR TABLESPACE TS_REG08_PEMDB PAGESIZE 8K BUFFERPOOL PEMDB_08KBP;
CREATE BUFFERPOOL PEMDB_16KBP IMMEDIATE SIZE 1000 PAGESIZE 16K;
CREATE REGULAR TABLESPACE TS_REG16_PEMDB PAGESIZE 16K BUFFERPOOL PEMDB_16KBP;
CONNECT RESET;